"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppStore, Lead } from '@/store/useAppStore';
import { MoreHorizontal, Plus, GripVertical, AlertCircle, Building2, UserCircle } from 'lucide-react';

const KANBAN_COLUMNS = [
  { id: 'NEW', title: 'New Leads', color: 'bg-emerald-500' },
  { id: 'CONTACTED', title: 'Contacted', color: 'bg-blue-500' },
  { id: 'QUALIFIED', title: 'Qualified', color: 'bg-purple-500' },
  { id: 'PROPOSAL', title: 'Proposal Sent', color: 'bg-[#F59E0B]' },
  { id: 'WON', title: 'Closed Won', color: 'bg-green-500' },
];

export default function LeadsKanban() {
  const { leads, updateLeadStatus, fetchLeads } = useAppStore();
  const [draggedLead, setDraggedLead] = useState<string | null>(null);

  useEffect(() => {
    fetchLeads();
  }, [fetchLeads]);

  const handleDragStart = (e: React.DragEvent, id: string) => {
    setDraggedLead(id);
    e.dataTransfer.setData('text/plain', id);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (e: React.DragEvent, status: Lead['status']) => {
    e.preventDefault();
    const id = e.dataTransfer.getData('text/plain');
    if (id && status) {
      updateLeadStatus(id, status);
    }
    setDraggedLead(null);
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex justify-between items-center mb-8 shrink-0">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight mb-2">Lead Pipeline</h1>
          <p className="text-[#A8A8A8] text-sm">Manage requirements generated by NOVELLEYX AI.</p>
        </div>
        <button className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-white/10 hover:bg-white/20 text-white font-bold text-sm transition-all shrink-0 border border-white/10">
          <Plus size={16} />
          <span>Manual Entry</span>
        </button>
      </div>

      <div className="flex-1 flex gap-6 overflow-x-auto pb-6 custom-scrollbar items-start">
        {KANBAN_COLUMNS.map(col => (
          <div 
            key={col.id} 
            className="flex-shrink-0 w-80 flex flex-col max-h-full bg-white/[0.02] border border-white/5 rounded-3xl overflow-hidden"
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, col.id as Lead['status'])}
          >
            {/* Column Header */}
            <div className="p-5 border-b border-white/5 flex justify-between items-center bg-[#0A0A0A]">
              <div className="flex items-center gap-3">
                <div className={`w-2 h-2 rounded-full ${col.color} shadow-[0_0_10px_currentColor]`} />
                <h3 className="font-bold text-white text-sm uppercase tracking-wider">{col.title}</h3>
                <span className="bg-white/10 text-[#A8A8A8] text-xs font-bold px-2 py-0.5 rounded-full">
                  {leads.filter(l => l.status === col.id).length}
                </span>
              </div>
              <button className="text-[#A8A8A8] hover:text-white transition-colors">
                <MoreHorizontal size={16} />
              </button>
            </div>

            {/* Column Body */}
            <div className="flex-1 p-4 overflow-y-auto space-y-4 custom-scrollbar min-h-[200px]">
              <AnimatePresence>
                {leads.filter(l => l.status === col.id).map(lead => (
                  <motion.div
                    key={lead.id}
                    layout
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    transition={{ type: "spring", stiffness: 400, damping: 25 }}
                    draggable
                    onDragStart={(e: any) => handleDragStart(e, lead.id)}
                    onDragEnd={() => setDraggedLead(null)}
                    className={`bg-[#121212] border ${draggedLead === lead.id ? 'border-[#F59E0B] opacity-50' : 'border-white/10'} rounded-2xl p-5 cursor-grab active:cursor-grabbing hover:border-white/20 transition-colors shadow-lg relative group`}
                  >
                    <div className="absolute top-5 right-5 text-neutral-600 group-hover:text-neutral-400 transition-colors">
                      <GripVertical size={16} />
                    </div>

                    <div className="mb-4 pr-6">
                      <h4 className="font-bold text-white text-base leading-tight mb-2 truncate" title={(lead as any).name || lead.goal}>{(lead as any).name || lead.goal}</h4>
                      
                      {/* Client Info Context */}
                      <div className="flex flex-col gap-1 mb-2">
                        {(lead as any).company && (
                          <div className="flex items-center gap-1.5 text-xs text-neutral-400">
                            <Building2 size={12} className="text-[#F59E0B]" />
                            <span className="truncate">{(lead as any).company}</span>
                          </div>
                        )}
                        {(lead as any).email && (
                          <div className="flex items-center gap-1.5 text-xs text-neutral-400">
                            <UserCircle size={12} className="text-[#F59E0B]" />
                            <span className="truncate">{(lead as any).email}</span>
                          </div>
                        )}
                      </div>

                      <p className="text-xs text-[#A8A8A8] line-clamp-2">{lead.problem}</p>
                    </div>

                    <div className="flex flex-wrap gap-2 mb-4">
                      {lead.recommended_services.map(svc => (
                        <span key={svc} className="text-[10px] font-semibold tracking-wide uppercase px-2 py-1 rounded bg-white/5 text-neutral-300 border border-white/5 truncate max-w-full">
                          {svc}
                        </span>
                      ))}
                    </div>

                    <div className="flex items-center justify-between pt-4 border-t border-white/5 mt-auto">
                      <div className="flex items-center gap-1.5">
                        <AlertCircle size={14} className={lead.complexity === 'HIGH' ? 'text-red-400' : lead.complexity === 'MEDIUM' ? 'text-yellow-400' : 'text-emerald-400'} />
                        <span className="text-[10px] font-bold text-[#A8A8A8] uppercase tracking-wider">AI: {lead.complexity}</span>
                      </div>
                      <span className="text-[10px] text-neutral-500 font-medium">
                        {new Date(lead.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
